<?php
/**
 * Copyright © 2021 magerubik.com. All rights reserved.
 * @author Magerubik Team <info@magerubik.com>
 * @package Magerubik_Blog
 * @var $block \Magerubik\Blog\Block\Sidebar\Archive
 */
?>
<?php
	$_months = $block->getMonths();
?>
<?php if (count($_months)) { ?>
<div class="sidebar-post">
	<div class="widget widget-post-cat">
		<div class="block-title">
			<strong><?php echo __('Archive') ?></strong>
		</div>
		<ul class="nav-list archive-blog-list">
			<?php foreach ($_months as $time) { ?>
				<?php
					$title = $block->getMonth($time).' '.$block->getYear($time);
					$title = $block->escapeHtml($title, null, true);
				?>
				<li>
					<a title="<?php echo __('Archive %s', $title) ?>" class="archive-item-link" href="<?php echo $block->getTimeUrl($time) ?>">
						<?php echo $title; ?>
					</a>
				</li>
			<?php } ?>
		</ul>
	</div>
</div>
<?php } ?>