<?php
/**
 * Copyright © 2021 magerubik.com. All rights reserved.
 * @author Magerubik Team <info@magerubik.com>
 * @package Magerubik_Blog
 * @var $block \Magerubik\Blog\Block\Sidebar\Recent
 */
	$_postCollection = $block->getPostCollection();
?>
<?php if ($_postCollection->count()) { ?>
<div class="sidebar-post"> 
	<div class="widget widget-recent-blog" data-bind="scope: 'recemt-posts'">
		<div class="block-title">
			<strong><?php echo __('Latest Blog Post');?></strong>
		</div>
		<ul class="nav-list recent-blog-list">
			<?php foreach ($_postCollection as $_post) { ?>
				<li>
					<div class="abs-img">
						<a title="<?php echo $block->escapeHtml($_post->getTitle()) ?>" href="<?php echo $_post->getPostUrl() ?>">
							<img class="zoom-eff" src="<?php echo $_post->getThumbnailimageSrc() ?>" alt="<?php echo $block->escapeHtml($_post->getTitle()) ?>">
						</a>
					</div>
					<div class="post-tab-info">
						<h3><a href="<?php echo $_post->getPostUrl() ?>"><?php echo $block->escapeHtml($_post->getTitle()) ?></a></h3>
						<span class="time-text d-block"><?php echo date('F d Y', strtotime($_post->getPublishTime())); ?></span>
					</div>
				</li>
			<?php } ?>
		</ul>
	</div>
</div>
<?php } ?>