<?php
/**
 * Copyright © 2021 magerubik.com. All rights reserved.
 * @author Magerubik Team <info@magerubik.com>
 * @package Magerubik_Blog
 * @var $block \Magerubik\Blog\Block\Post\PostList
 */
$_postCollection = $block->getPostCollection();
?>
<?php if (!$_postCollection->count()): ?>
    <div class="message info empty"><div><?php echo __('We can\'t find posts matching the selection.') ?></div></div>
<?php else: ?>
    <?php echo $block->getAdditionalHtml() ?>
    <div class="post-list-wrapper">
        <?php $iterator = 1; ?>
        <div class="blog-list-post">
            <?php foreach ($_postCollection as $_post): ?>
                <?php echo $block->getPostHtml($_post) ?>
            <?php endforeach; ?>
        </div>
    </div>
    <?php echo $block->getToolbarHtml() ?>
<?php endif; ?>